In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('CARD_HIST12345.csv')

In [3]:
df = df[['STAT_NCODE', 'NAME', 'TAXPAYER_NCODE', 'REGNUM_NCODE', 'UK']]

In [4]:
df_final = pd.DataFrame()

In [14]:
df_excel = pd.read_excel('46.71/2018.xlsx')
df_excel.columns = df_excel.iloc[2]
df_excel = df_excel.drop([0, 1, 2], axis=0)

a = ['2018, Нематериальные активы, RUB', '2018, Основные средства , RUB', '2018, Доходные вложения в материальные ценности, RUB', '2018, Долгосрочные финансовые вложения, RUB', '2018, Отложенные налоговые активы, RUB', '2018, Прочие внеоборотные активы, RUB', '2018, Внеоборотные активы, RUB', '2018, Чистые активы, RUB', '2018, Запасы, RUB', '2018, Дебиторская задолженность, RUB', '2018, Краткосрочные финансовые вложения, RUB', '2018, Денежные средства и денежные эквиваленты, RUB', '2018, Прочие оборотные активы, RUB', '2018, Оборотные активы, RUB', '2018, Активы  всего, RUB', '2018, Собственные акции, выкупленные у акционеров, RUB', '2018, Переоценка внеоборотных активов, RUB', '2018, Доходы будущих периодов , RUB']
b = ['INTANGIBLE_ASSETS_ATM', 'FIXED_ASSETS_ATM', 'PROFITABLE_INVESTMENTS_ATM', 'LONGTERM_INVESTMENTS_ATM', 'DEFERRED_TAX_ASSETS_ATM', 'OTHER_NONCURRENT_ASSETS_ATM', 'NONCURRENT_ASSETS_ATM', 'NET_ASSETS_ATM', 'RESERVES_ATM', 'RECEIVABLES_ATM', 'SHORTTERM_INVESTMENTS_ATM', 'CASH_CASH_EQUIVALENTS_ATM', 'OTHER_CURRENT_ASSETS_ATM', 'CURRENT_ASSETS_ATM', 'TOTAL_ASSETS_ATM', 'TREASURY_SHARES_ATM', 'REVALUATION_NONCURRENT_ASSETS_ATM', 'REVENUE_FUTURE_PERIODS_ATM']
c = ['Наименование', 'Регистрационный номер', 'Код налогоплательщика', 'Код статистики']
d = ['NAME', 'REGNUM_NCODE', 'TAXPAYER_NCODE', 'STAT_NCODE']
# a += c
ac = a
ac += c
# b += d
df_excel = df_excel[ac]
dic = dict(zip(ac, b))
df_excel.rename(columns=dic, inplace=True)
df_excel['Регистрационный номер'] = df_excel['Регистрационный номер'].fillna('-1').astype(int)
df_excel['Код налогоплательщика'] = df_excel['Код налогоплательщика'].fillna('-1').astype(int)
df_excel['Код статистики'] = df_excel['Код статистики'].fillna('-1').astype(int)
df_excel[b] = df_excel[b].fillna('-1').astype(float)

df_excel = df_excel.merge(df, how='inner', left_on = ['Наименование', 'Регистрационный номер', 'Код налогоплательщика', 'Код статистики'], right_on = ['NAME', 'REGNUM_NCODE', 'TAXPAYER_NCODE', 'STAT_NCODE'])
df_excel.drop(['Наименование', 'NAME', 'Регистрационный номер', 'Код налогоплательщика', 'STAT_NCODE', 'NAME', 'TAXPAYER_NCODE', 'REGNUM_NCODE', 'Код статистики'], axis=1, inplace=True)
df_excel.rename(columns={'UK': 'CARD_UK'}, inplace=True)

df_excel['VALUE_DAY'] = '20181231' #CHECK
df_excel['AS_OF_DAY'] = '20191214 12:20:00'
df_excel['DELETED_FLAG'] = 'N'
df_excel['JOB_INSERT'] = -1
df_excel['JOB_UPDATE'] = -1

df_final = pd.concat([df_final, df_excel], ignore_index=True)

In [15]:
df_final

,INTANGIBLE_ASSETS_ATM,FIXED_ASSETS_ATM,PROFITABLE_INVESTMENTS_ATM,LONGTERM_INVESTMENTS_ATM,DEFERRED_TAX_ASSETS_ATM,OTHER_NONCURRENT_ASSETS_ATM,NONCURRENT_ASSETS_ATM,NET_ASSETS_ATM,RESERVES_ATM,RECEIVABLES_ATM,...,TOTAL_ASSETS_ATM,TREASURY_SHARES_ATM,REVALUATION_NONCURRENT_ASSETS_ATM,REVENUE_FUTURE_PERIODS_ATM,CARD_UK,VALUE_DAY,AS_OF_DAY,DELETED_FLAG,JOB_INSERT,JOB_UPDATE
0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1005019,20091231,20191214 12:20:00,N,-1,-1
1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1005020,20091231,20191214 12:20:00,N,-1,-1
2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1005021,20091231,20191214 12:20:00,N,-1,-1
3,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1005022,20091231,20191214 12:20:00,N,-1,-1
4,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1005023,20091231,20191214 12:20:00,N,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57938,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1006540,20181231,20191214 12:20:00,N,-1,-1
57939,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1006541,20181231,20191214 12:20:00,N,-1,-1
57940,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-79000.0,171000.0,1631000.0,...,2072000.0,-1.0,-1.0,-1.0,1006542,20181231,20191214 12:20:00,N,-1,-1
57941,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1006543,20181231,20191214 12:20:00,N,-1,-1
57942,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,1006544,20181231,20191214 12:20:00,N,-1,-1

In [16]:
dff = df_final
dff.index.names = ['UK']

In [17]:
dff.to_csv('ASSETS_STAT.csv')